### ISSUE TITLE
Chrome and Konsole opens on secondary monitor - persists through reboot

### ISSUE THREAD

**Issue by vegarab** [Jazqa/kwin-quarter-tiling#23] opened 2017-08-14 11:03 UTC
Unsure exactly what caused this, but it seems that opening a Chrome window on the main monitor, toggling float off to move to and maximize it on the secondary screen broke parts of the script.
All Konsole and Chrome windows now open on the secondary monitor - with script off and on. Chrome cannot be moved back when float is off. It always snaps back to the secondary monitor. Floating it, moving it over to the main monitor and unfloating it is the only way I can now move Chrome over to the main monitor. 
I have disabled borders, so I cannot move or manipulate the Konsole window. I am therefore unable to move it away from the secondary monitor. 

This persists through script restart, session restart and system reboots. It practically broke the script for me, since Chrome and Konsole can no longer be used on the main monitor.

**Comment by Jazqa** [comment] 2017-08-14 14:19
Chrome and Konsole starting on a different screen is weird, I'll check if something's up with the initial screen of new windows.

I'm occasionally experiencing the inability to move windows between screens as well. There's something wrong with KWin's geometries and attempting to resize the window (both horizontally and vertically, just in case) seems to fix the geometries and allow a window to be moved between screens again. I've been experiencing this bug since the beginning and I have no idea what's causing it. If using borders, the bug is visible and the bugged windows are missing their vertical borders. I can't say for sure we are having the same issue but it's worth a shot! 

>I have disabled borders, so I cannot move or manipulate the Konsole window. I am therefore unable to move it away from the secondary monitor.

Can you manipulate it by holding Alt and pressing left and right Mouse Buttons?

**Comment by vegarab** [comment] 2017-08-14 14:45
> Can you manipulate it by holding Alt and pressing left and right Mouse Buttons?

Awesome, this works as a workaround. It seems that I just initially need to move the first Konsole and Chrome window that is opened in that session to the main monitor, and then new windows stay there (moving them over by floating, moving over, and unfloating it again). It needs to be done on the first window of a new session though.

**Comment by Jazqa** [comment] 2017-08-14 18:52
I changed the behaviour of new windows and as a result creating windows on different screens works better. I'm not sure if this issue is fixed, as I was not able to reproduce it, but it's worth a shot.

**Comment by Jazqa** [comment] 2017-08-21 11:15
I faced similar issues with Konsole today. My issues (and partly yours too, as they persist without the script) were caused by KDE. 

Whenever a window is started, if it's vertically or horizontally too large for one screen, KDE tries to interfere. In your case Chrome and Konsole start on main display, vertically adjusted for second display. The size makes KDE move the window to the second display while the script thinks it got added to the first one.

I'll try to fix this today.

**Comment by vegarab** [comment] 2017-08-21 11:42
I didn't think of this earlier, but it might be a good idea to add: My main monitor is a 3840x2160, and the vertical one is a 1080p monitor. That might also contribute to the issue of a window being too large for one screen.

**Comment by Jazqa** [comment] 2017-08-21 11:49
That's definitely the cause. I had similar issues when I used a 1280x720 monitor with 1920x1080 ones. I'll see if I can come up with a solution.

As an unrelated note, typically windows should stat on the active display (the one with cursor)

**Comment by Jazqa** [comment] 2017-08-21 12:41
Apparently KWin applies the size before the script does. You have to find a way to start Chrome and Konsole with a size smaller than your smallest display in order fix the issue both, with and without the script.

One potential solution would be adding a Window Rule for problematic programs. "Window Rules" » New » Detect Window Properties » Size & Position » Size. Script-wise, the size you enter makes no difference, as long as it's horizontally and vertically smaller than your smallest display, because the window is going to get tiled either way.

If the following doesn't solve the issue, I'll keep trying to find more solutions.

**Comment by vegarab** [comment] 2017-08-21 14:36
I'll give this a shot once I am back at my desktop computer. For now, I am still using the workaround that I outlined earlier.

**Comment by vegarab** [comment] 2017-08-30 18:52
This solved the issue.

**Comment by Jazqa** [comment] 2017-08-31 13:04
I'll close this for now as it's really a KWin issue and there's not much I can do about it. The method above should work as a workaround for the issue, were you using the script or not. Sadly, I can't alter the size of a window before a window is added or after it's closed, so the workaround above must be used.

Another way to avoid the issue is to manually float a large window before closing it as it shrinks the size down a bit. I've tried to automate this to happen every time a windows is closed but as I mentioned above, it's not possible.

**Closed as completed by Jazqa** 2017-08-31 13:04 UTC
Labels: bug
