### ISSUE TITLE
Wrong height of a new window

### ISSUE THREAD

**Issue by andreyorst** [Jazqa/kwin-quarter-tiling#33] opened 2017-10-01 08:55 UTC
Hello, thanks for great plugin.

Really strange behavior of opening a new window. For example if I open 2, and make one wider, new terminal will split one of those in half:
step 1:
![image](https://user-images.githubusercontent.com/19470159/31053084-0776af68-a69e-11e7-94c3-e0b2c21e8488.png)
step 2:
![image](https://user-images.githubusercontent.com/19470159/31053086-148c5428-a69e-11e7-8b04-6ef86037761b.png)
Thats ok. But if i do the same with telegram an chromium any new window shat should split chomium in half would shirnk chromium and use 1/3 of screen like so:
step 1:
![image](https://user-images.githubusercontent.com/19470159/31053101-448d97f4-a69e-11e7-8f74-9287ec46ad25.png)
step 2:
![image](https://user-images.githubusercontent.com/19470159/31053116-a7f79380-a69e-11e7-89d2-416a4d7fd2bb.png)

Or if chromium on the left it causes different behavior:
step 1:
![image](https://user-images.githubusercontent.com/19470159/31053127-d33d82b6-a69e-11e7-8815-629b246e5a41.png)
step 2:
![image](https://user-images.githubusercontent.com/19470159/31053132-e43aab16-a69e-11e7-9e54-26adee8c77ff.png)

I think it is related to small app setting. Because if telegram is not open it works normally

**Comment by Jazqa** [comment] 2017-10-01 13:28
This is caused by the small programs and autosize settings. Small programs get automatically switched to the right pane and other programs automatically adjust to the size of the small programs – causing this silly interaction. 

I'm going to fix this by disabling the automatic switch and automatically shrinking small programs in case they are too large. I'll play around the settings tonight and commit a fix by tomorrow!

**Comment by andreyorst** [comment] 2017-10-01 14:04
Whoa, thanks a lot!

Only thing i could wish that this kwin script could become something like a "bspwm for plasma"

**Comment by Jazqa** [comment] 2017-10-01 15:14
@andreyorst, since creating the script, I've tried multiple window managers and I've become a better programmer. I'd like to re-write most of the script in order to support multiple layouts and tiling algorithms but I'm extremely busy right now.

I'm still fixing bugs and implementing minor features whenever issues are filed, but unfortunately huge changes such as new layouts and tiling algorithms will have to wait until I have gotten all the important work out of the way.

**Comment by Jazqa** [comment] 2017-10-02 19:31
I pushed a quick fix. It should stop "Small Programs" perceiving their size if they are too large. That being said, it was a quick fix as I had a super busy day. I'll try to adjust the "Small Programs" and "Autosize" code further as soon as I have the time.

**Comment by andreyorst** [comment] 2017-10-02 21:00
still works not quite as I expected. I decided to switch off "small programs" for telegram, but still, other apps are not cutting telegram in half. But now the behavior is identical as  when "small apps" is on. 
![image](https://user-images.githubusercontent.com/19470159/31099093-8973a9e6-a7cd-11e7-8513-2d7901699bb3.png)
Terminal isn't sized properly. 

Well, i'll use it as is by now, because i'm not often use more than 2 apps on one desktop, so it is not a big problem for me.

**Comment by Jazqa** [comment] 2017-10-02 21:23
This is getting odd. I replicated the issue easily before the commit but now I can't seem to replicate it anymore. After the changes, Telegram is getting cut in half in situations like this. I might be too tired to notice something obvious 😴 I'll get some sleep and get back to it in the morning. I'll also make some time available tomorrow to fix this issue, I can't leave it like this. Thanks for your help with the issue!

> I decided to switch off "small programs" for telegram, but still, other apps are not cutting telegram in half. But now the behavior is identical as when "small apps" is on.

This is extremely weird, did you restart the script after changing the configuration (can be done by unticking the box, hitting apply, ticking the box and hitting apply again or simply by running `kwin --replace`)? Unfortunately, the script can't read configuration changes automatically.

**Comment by andreyorst** [comment] 2017-10-02 21:44
OHHHH I figured it out. Pardon me, I've used <kbd>ctrl</kbd>+<kbd>Y</kbd> to change telegram's size, and it changes both width and height for a window, which is not obvious when you use only 2 apps per desktop. That is causing my "new" problem.

**Comment by Jazqa** [comment] 2017-10-02 21:46
Ahh, yes. I've tried to keep the keybindings to minimum so there's only one shortcut for expanding a window and one shortcut for shrinking a window. Adding and dividing the keybindings for all four directions would be extremely easy though, if someone feels like it's needed.

**Comment by andreyorst** [comment] 2017-10-02 21:57
yeah i defined my keybindings like so:
<kbd>super</kbd>+<kbd>h</kbd> - change focus to left window
<kbd>super</kbd>+<kbd>j</kbd> - change focus to bottom window
<kbd>super</kbd>+<kbd>k</kbd> - change focus to top window
<kbd>super</kbd>+<kbd>l</kbd> - change focus to right window

<kbd>Ctrl</kbd>+<kbd>super</kbd>+<kbd>h</kbd> - swap left window
...

and to change size i would love something like in KDE Plasma with <kbd>Alt</kbd>
<kbd>Alt</kbd>+<kbd>super</kbd>+<kbd>h</kbd> - extend width to left
etc

By the way, I enabled "small apps" for telegram, and set its size with mouse. But when i swap tg with chromium...
![image](https://user-images.githubusercontent.com/19470159/31101304-bdafd506-a7d5-11e7-9ec1-cb4aa1f4503b.png)

this happens

**Comment by Jazqa** [comment] 2017-10-02 22:03
Thanks for the suggestion, I'll add the Alt + Super + H/J/K/L keybindings tomorrow or the day after. Can you post a screenshot of your configuration and I'll see if I can fix the Telegram/Chromium swap before I hit the bed. It's most likely a weird interaction with the "Autosize" option I've overlooked.

**Comment by andreyorst** [comment] 2017-10-02 22:15
Yeah, no problem :D
![image](https://user-images.githubusercontent.com/19470159/31101624-3e20f7c8-a7d7-11e7-8eb8-6b81a035457b.png)
Pretty much defaults:
![image](https://user-images.githubusercontent.com/19470159/31101698-802e1fe2-a7d7-11e7-8de8-eaa66c023a10.png)

Screencast:

[tiling.zip](https://github.com/Jazqa/kwin-quarter-tiling/files/1350579/tiling.zip)

**Comment by Jazqa** [comment] 2017-10-02 22:32
My god, that's absolutely awful! My bad 😳 

It should be **way better** now and I can finally get some sleep. Small Programs are a major pain in the ass though – especially with the existence of the "Autosize" option. I'm fairly certain most tiling window managers simply force windows to the tiles with little to no regard of their actual sizes. If you have any ideas how resizing and moving these programs should work, I'm open to suggestions!

**Comment by andreyorst** [comment] 2017-10-03 08:14
The problem is still there. Everithing as on a screencast. 

About behavior: maybe you should fit small program in a full-size invisible tile. So if new program opened it slices invisible tile, and small app changes its size.

**Comment by Jazqa** [comment] 2017-10-03 10:45
Curious. I changed multiple things seen in the screencast. (Autosize was occuring when you resized Telegram - it shouldn't anymore & resizing small programs shouldn't increase the width of their tiles unless they grow larger than the tile). Have you installed the script via the store or git? 

As for small programs, I'm doing it exactly like that. Small programs are placed on an invisible tile and either centered on that tile or to the edge of the tile (depending on the "Center" setting). If "Autosize" is enabled, the invisible tiles are automatically shrunk to small program's width and/or height depending on the situation.

Anyways, I'll keep working on this today!

**Comment by Jazqa** [comment] 2017-10-04 14:52
Okay. I spent the whole day with the script and this issue still exists. It is – kind of – intentional. Size of the "Small Programs" is fixed and the opposite non-"Small Program" will respect their (vertical) sizes and adjust itself according to them. You can either shrink the "Small Program" manually or remove it from the "Small Programs" category (until I figure out a better approach – I'll probably need to add some nasty `if`-cases for situations where "Small Programs" can get adjusted).

Small clients are a pain in the ass (especially moving and resizing) but overall, the size behaviour should feel way more **consistent** now. **Not necessarily better**, but more consistent. Vast empty space around "Small Programs" happens because they occupy a regular tile. If you place a tiny "Small Program" on a huge tile, it'll have a ton of empty space. Empty space can be cut by resizing another client towards a "Small Program". Horizontally swapping a "Small Program" with a large tile causes this, as the tiles remain the same but the contents of the tiles change.

I'll keep working on this tomorrow. I'm sure I can find **a sane, clean and consistent** way to handle "Small Programs". Right now the biggest problems are the different handling of horizontal and vertical panes, resizing "Small Programs" (it would be amazing if I could display the empty tile, automatically move the cursor to the edge of the tile and allow the user to resize the tile – unfortunately this is not possible) and adjusting the empty space around "Small Programs". **I appreciate all feedback here – coding the changes is not an issue, figuring out the most sensible approach is.** I wasted the whole day trial-and-erroring different "Small Programs" and "Autosize" behaviour without finding a one that felt consistent and user-friendly.

If not using "Small Programs" – everything should work consistently as expected.

**Comment by kupiqu** [comment] 2017-10-06 13:01
With all due respect, I don't like the new implementation, neither I think it is consistent. I use several Small clients, most of the times they share a same desktop and screen. Before, I couldn't make a small client to step on other small clients, which is now possible. I think that it is incongruent as Small clients are supposed to have a fixed size, or at least to not obey automatic tiling in terms of size.

In fact, this was for me a nice property that I used when I found a sort of a bug, when opening/closing some apps, improperly changed the size of small clients adjusting it to other small clients (this was not very frequent and I could not find a way to reproduce it, so that's why I haven't filled an issue about this yet). However, this new behavior of the script makes it impossible to readjust the size of the small clients, because of what I said before, they step on each other, so increasing the size of one, automatically reduces the sizes of others.

**Comment by kupiqu** [comment] 2017-10-06 13:21
In the approach that I would like best, small clients should never be resized in the context of the script unless their size is manually increased so they start stepping on quarters that are actively used by other windows. In this case, its size should be constrained to fit only the free space (free quarters).

Then perfection for me (see issue #10) would be if small clients (of small enough size that fit together in a same quarter), would in fact share a same quarter, but only when one, or more, other windows are present (so these windows benefit of an extra free quarter).

I am not suggesting to put them in the same quarter by default because in absence of other windows, they may look bad (too close one from the other in the context of an, otherwise, empty desktop).

**Comment by kupiqu** [comment] 2017-10-06 13:29
Also, resetting the script now doesn't restore the size of small clients, which was the case before. I'm using this feature quite a lot. Could we get it back?

**Comment by kupiqu** [comment] 2017-10-06 13:37
I am thinking now that perhaps distinct users utilize small clients seeking different goals, which may not be mutually compatible.

Wondering whether it would make sense to distinguish a couple of potential use cases and then decide whether to separate the small client category into easier to manage policies?

**Comment by Jazqa** [comment] 2017-10-06 14:48
@kupiqu, thanks for the feedback, You can get back all of the features you enjoy, don't worry about it. I'll work with the script today and tomorrow, reverting and improving some of the features. 

Unfortunately clients occupying the same tile will have to wait two or three weeks. It's quite a job and the next two weeks are extremely busy. I'll promise to implement it after ;)

**Comment by Jazqa** [comment] 2017-10-07 08:29
@andreyorst, I've fixed this. In cases like this, Telegram gets shrunk to a quarter. I'm probably leaving the current behaviour as default and adding an option for the old behaviour with fixed-size "Small Programs".

**Comment by Jazqa** [comment] 2017-10-11 12:05
@kupiqu, I'll close this as the issue is fixed. Let's move further discussion back to #10. Unfortunately I've been too busy with my bachelor's and haven't done anything since I said I'd revert some of the changes five days ago. The old features are still available through the releases-page though. I'll try to find some time tomorrow or the day after for the issue!

**Closed as completed by Jazqa** 2017-10-11 12:05 UTC

**Comment by kupiqu** [comment] 2017-10-11 12:22
Sounds great, thank you!
